### ISSUE TITLE
I'm not receiving payments

### ISSUE THREAD

**Issue by juliolvfilho** [billaue2/cryptonote-aeon-pool#2]
Hi sumominer staff!
I'm mining AEON in your pool (aeon.sumominer.com).
I'm not receiving payments over 24 hours and my pending balance is already more than 20 AEON.
Could you give some explanation about that?
So I can rest easy.
Thanks for listening.

**Comment by billaue2** [comment]
There is an problem with the pool wallet, we're investigating why. Payouts will be resumed soon. Thanks for report.

**Comment by billaue2** [comment]
Payments sent.
